<h1 align="center"><b> Comparative Analysis of Breast Cancer and Parkinson’s Disease using EDA, ML, DL & NLP</b></h1>


# The objective of this project is to perform a comprehensive comparative analysis of two distinct medical datasets: Breast Cancer and Parkinson’s Disease. The study involves data loading, cleaning, and in-depth exploration using Exploratory Data Analysis (EDA) and statistical techniques. Additionally, Machine Learning, Deep Learning, and Natural Language Processing (NLP) are applied to examine feature behavior, structural differences, and biological relevance. The focus is on understanding patterns and insights within the data rather than building predictive models.
</p>

# 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = 'colab'
from scipy.stats import ttest_ind, chi2_contingency, pearsonr
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')
print("Libraries imported.")

# 2. Load Datasets

In [ ]:
# Breast Cancer Dataset
df = pd.read_csv("/content/data.csv")

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
# Parkinson's Dataset
parkinsons_df = pd.read_csv("/content/parkinsons.data")

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

# 3. Data Cleaning & Overview

# 3.1 Missing Values

In [ ]:
print("Breast Cancer missing values:\n", df_bc.isnull().sum().sum())
print("Parkinson's Disease missing values:\n", df_pd.isnull().sum().sum())

0
0

# 3.2 Duplicates

In [ ]:
print(f"Breast Cancer duplicates: {df_bc.duplicated().sum()}")
print(f"Parkinson's Disease duplicates: {df_pd.duplicated().sum()}")

# 3.3 Target Distribution

In [ ]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Breast Cancer', "Parkinson's Disease"))
fig.add_trace(go.Pie(labels=df_bc['target_label'].value_counts().index,
                     values=df_bc['target_label'].value_counts().values), row=1, col=1)
fig.add_trace(go.Pie(labels=['Healthy (0)', 'Parkinson (1)'],
                     values=df_pd['target'].value_counts().values), row=1, col=2)
fig.update_layout(title='Target Distribution Comparison')
fig.show()

# 3.4 Feature Data Types

In [ ]:
print("Breast Cancer data types:")
print(df_bc.dtypes.value_counts())
print("\nParkinson's Disease data types:")
print(df_pd.dtypes.value_counts())

# 4. Exploratory Data Analysis (EDA)

# 4.1 Dataset Dimensions & Feature Counts

In [ ]:
print(f"Breast Cancer: {df_bc.shape[1]-2} features, {df_bc.shape[0]} samples")
print(f"Parkinson's Disease: {df_pd.shape[1]-1} features, {df_pd.shape[0]} samples")

# 4.2 Statistical Summaries

In [ ]:
display(df_bc.describe().T)

In [ ]:
display(df_pd.describe().T)

# 4.3 Feature Distributions (Violin Plots)

In [ ]:
# Select first 4 features from each dataset
bc_features = df_bc.columns[:4]
pd_features = df_pd.columns[:4]

fig = make_subplots(rows=2, cols=4, subplot_titles=list(bc_features) + list(pd_features))

for i, col in enumerate(bc_features):
    for target_val, color in zip([0,1], ['red','blue']):
        subset = df_bc[df_bc['target']==target_val][col]
        fig.add_trace(go.Violin(y=subset, name=f'Target {target_val}', marker_color=color, showlegend=False), row=1, col=i+1)

for i, col in enumerate(pd_features):
    for target_val, color in zip([0,1], ['red','blue']):
        subset = df_pd[df_pd['target']==target_val][col]
        fig.add_trace(go.Violin(y=subset, name=f'Target {target_val}', marker_color=color, showlegend=False), row=2, col=i+1)

fig.update_layout(height=800, title='Feature Distributions by Target')
fig.show()

# 4.4 Correlation Heatmaps

In [ ]:
# Breast Cancer (first 10 features)
corr_bc = df_bc.iloc[:,:10].corr()
fig = px.imshow(corr_bc, text_auto=True, title='Breast Cancer: Correlation Heatmap (First 10 Features)',
                color_continuous_scale='RdBu', zmin=-1, zmax=1)
fig.show()

In [ ]:
# Parkinson's Disease (all features)
corr_pd = df_pd.drop('target', axis=1).corr()
fig = px.imshow(corr_pd, title="Parkinson's Disease: Correlation Heatmap",
                color_continuous_scale='RdBu', zmin=-1, zmax=1)
fig.show()

# 4.5 Principal Component Analysis (PCA)

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Breast Cancer
scaler_bc = StandardScaler()
X_bc_scaled = scaler_bc.fit_transform(df_bc.drop(['target', 'target_label'], axis=1))
pca_bc = PCA(n_components=2)
pca_bc_result = pca_bc.fit_transform(X_bc_scaled)
df_bc_pca = pd.DataFrame(pca_bc_result, columns=['PC1', 'PC2'])
df_bc_pca['target'] = df_bc['target_label']

fig = px.scatter(df_bc_pca, x='PC1', y='PC2', color='target',
                 title='Breast Cancer: PCA Visualization')
fig.show()

In [ ]:
# Parkinson's Disease
scaler_pd = StandardScaler()
X_pd_scaled = scaler_pd.fit_transform(df_pd.drop('target', axis=1))
pca_pd = PCA(n_components=2)
pca_pd_result = pca_pd.fit_transform(X_pd_scaled)
df_pd_pca = pd.DataFrame(pca_pd_result, columns=['PC1', 'PC2'])
df_pd_pca['target'] = df_pd['target'].map({0:'Healthy',1:'Parkinson'})

fig = px.scatter(df_pd_pca, x='PC1', y='PC2', color='target',
                 title="Parkinson's Disease: PCA Visualization")
fig.show()

# 4.6 Class Separability (t‑SNE)

In [ ]:
from sklearn.manifold import TSNE

# Breast Cancer
tsne_bc = TSNE(n_components=2, random_state=42)
tsne_bc_result = tsne_bc.fit_transform(X_bc_scaled)
df_bc_tsne = pd.DataFrame(tsne_bc_result, columns=['tSNE1', 'tSNE2'])
df_bc_tsne['target'] = df_bc['target_label']
fig = px.scatter(df_bc_tsne, x='tSNE1', y='tSNE2', color='target',
                 title='Breast Cancer: t‑SNE Visualization')
fig.show()

In [ ]:
# Parkinson's Disease
tsne_pd = TSNE(n_components=2, random_state=42)
tsne_pd_result = tsne_pd.fit_transform(X_pd_scaled)
df_pd_tsne = pd.DataFrame(tsne_pd_result, columns=['tSNE1', 'tSNE2'])
df_pd_tsne['target'] = df_pd['target'].map({0:'Healthy',1:'Parkinson'})
fig = px.scatter(df_pd_tsne, x='tSNE1', y='tSNE2', color='target',
                 title="Parkinson's Disease: t‑SNE Visualization")
fig.show()

# 5. Statistical Testing

# 5.1 T‑test for Feature Differences Between Classes

In [ ]:
# Breast Cancer: select a few features
bc_features_to_test = ['mean radius', 'mean texture', 'mean perimeter', 'mean area']
ttest_bc_results = []
for col in bc_features_to_test:
    group1 = df_bc[df_bc['target']==0][col]
    group2 = df_bc[df_bc['target']==1][col]
    t_stat, p_val = ttest_ind(group1, group2, equal_var=False)
    ttest_bc_results.append({'Feature': col, 'T-statistic': t_stat, 'P-value': p_val})
pd.DataFrame(ttest_bc_results)

In [ ]:
# Parkinson's Disease: select a few features
pd_features_to_test = ['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)']
ttest_pd_results = []
for col in pd_features_to_test:
    group1 = df_pd[df_pd['target']==0][col]
    group2 = df_pd[df_pd['target']==1][col]
    t_stat, p_val = ttest_ind(group1, group2, equal_var=False)
    ttest_pd_results.append({'Feature': col, 'T-statistic': t_stat, 'P-value': p_val})
pd.DataFrame(ttest_pd_results)

# 6. Machine Learning (Classification)

# 6.1 Prepare Data

In [ ]:
# Breast Cancer
X_bc = df_bc.drop(['target', 'target_label'], axis=1)
y_bc = df_bc['target']
X_bc_train, X_bc_test, y_bc_train, y_bc_test = train_test_split(X_bc, y_bc, test_size=0.2, random_state=42, stratify=y_bc)
scaler_bc_ml = StandardScaler()
X_bc_train_scaled = scaler_bc_ml.fit_transform(X_bc_train)
X_bc_test_scaled = scaler_bc_ml.transform(X_bc_test)

In [ ]:
# Parkinson's Disease
X_pd = df_pd.drop('target', axis=1)
y_pd = df_pd['target']
X_pd_train, X_pd_test, y_pd_train, y_pd_test = train_test_split(X_pd, y_pd, test_size=0.2, random_state=42, stratify=y_pd)
scaler_pd_ml = StandardScaler()
X_pd_train_scaled = scaler_pd_ml.fit_transform(X_pd_train)
X_pd_test_scaled = scaler_pd_ml.transform(X_pd_test)

# 6.2 Define Models

In [ ]:
models = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(n_estimators=100),
    'Gradient Boosting': GradientBoostingClassifier(),
    'SVM': SVC(probability=True)
}

# 6.3 Train & Evaluate on Breast Cancer

In [ ]:
results_bc = {}
for name, model in models.items():
    model.fit(X_bc_train_scaled, y_bc_train)
    y_pred = model.predict(X_bc_test_scaled)
    acc = accuracy_score(y_bc_test, y_pred)
    auc = roc_auc_score(y_bc_test, model.predict_proba(X_bc_test_scaled)[:,1])
    results_bc[name] = {'Accuracy': acc, 'AUC': auc}
    print(f"Breast Cancer - {name:20} | Accuracy: {acc:.4f} | AUC: {auc:.4f}")

# 6.4 Train & Evaluate on Parkinson's Disease

In [ ]:
results_pd = {}
for name, model in models.items():
    model.fit(X_pd_train_scaled, y_pd_train)
    y_pred = model.predict(X_pd_test_scaled)
    acc = accuracy_score(y_pd_test, y_pred)
    auc = roc_auc_score(y_pd_test, model.predict_proba(X_pd_test_scaled)[:,1])
    results_pd[name] = {'Accuracy': acc, 'AUC': auc}
    print(f"Parkinson's Disease - {name:20} | Accuracy: {acc:.4f} | AUC: {auc:.4f}")

# 6.5 Model Comparison Bar Charts

In [ ]:
res_bc_df = pd.DataFrame(results_bc).T.reset_index().rename(columns={'index': 'Model'})
res_bc_df['Dataset'] = 'Breast Cancer'
res_pd_df = pd.DataFrame(results_pd).T.reset_index().rename(columns={'index': 'Model'})
res_pd_df['Dataset'] = 'Parkinson\'s Disease'
combined = pd.concat([res_bc_df, res_pd_df])

fig = px.bar(combined, x='Model', y='Accuracy', color='Dataset', barmode='group',
             title='Model Accuracy Comparison')
fig.show()

# 7. Deep Learning (Neural Networks)

# 7.1 Breast Cancer Neural Network

In [ ]:
nn_bc = Sequential([
    Dense(128, activation='relu', input_shape=(X_bc_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])
nn_bc.compile(optimizer=Adam(0.001), loss='binary_crossentropy', metrics=['accuracy'])
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
history_bc = nn_bc.fit(X_bc_train_scaled, y_bc_train, epochs=100, batch_size=16, validation_split=0.2, callbacks=[early_stop], verbose=0)
loss_bc, acc_bc = nn_bc.evaluate(X_bc_test_scaled, y_bc_test, verbose=0)
print(f"Breast Cancer Neural Network Test Accuracy: {acc_bc:.4f}")

# 7.2 Parkinson's Disease Neural Network

In [ ]:
nn_pd = Sequential([
    Dense(64, activation='relu', input_shape=(X_pd_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])
nn_pd.compile(optimizer=Adam(0.001), loss='binary_crossentropy', metrics=['accuracy'])
history_pd = nn_pd.fit(X_pd_train_scaled, y_pd_train, epochs=100, batch_size=16, validation_split=0.2, callbacks=[early_stop], verbose=0)
loss_pd, acc_pd = nn_pd.evaluate(X_pd_test_scaled, y_pd_test, verbose=0)
print(f"Parkinson's Disease Neural Network Test Accuracy: {acc_pd:.4f}")

# 7.3 Neural Network Training History

In [ ]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Breast Cancer', "Parkinson's Disease"))
fig.add_trace(go.Scatter(y=history_bc.history['loss'], name='Train Loss'), row=1, col=1)
fig.add_trace(go.Scatter(y=history_bc.history['val_loss'], name='Val Loss'), row=1, col=1)
fig.add_trace(go.Scatter(y=history_pd.history['loss'], name='Train Loss'), row=1, col=2)
fig.add_trace(go.Scatter(y=history_pd.history['val_loss'], name='Val Loss'), row=1, col=2)
fig.update_layout(title='Neural Network Training Loss')
fig.show()

# 8. NLP on Feature Names

# 8.1 Combine Feature Names

In [ ]:
bc_features_text = ' '.join(df_bc.drop(['target', 'target_label'], axis=1).columns)
pd_features_text = ' '.join(df_pd.drop('target', axis=1).columns)
documents = [bc_features_text, pd_features_text]
labels = ['Breast Cancer', "Parkinson's Disease"]

# 8.2 TF‑IDF Vectorization

In [ ]:
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)
feature_names = vectorizer.get_feature_names_out()
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), index=labels, columns=feature_names)
tfidf_df

# 8.3 Heatmap of TF‑IDF Scores

In [ ]:
fig = px.imshow(tfidf_df, text_auto=True, title='TF‑IDF of Feature Names')
fig.show()

# 8.4 Word Cloud

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Breast Cancer word cloud
wc_bc = WordCloud(width=800, height=400, background_color='white').generate(bc_features_text)
plt.figure(figsize=(10,5))
plt.imshow(wc_bc, interpolation='bilinear')
plt.title('Breast Cancer Feature Names Word Cloud')
plt.axis('off')
plt.show()

In [ ]:
# Parkinson's Disease word cloud
wc_pd = WordCloud(width=800, height=400, background_color='white').generate(pd_features_text)
plt.figure(figsize=(10,5))
plt.imshow(wc_pd, interpolation='bilinear')
plt.title("Parkinson's Disease Feature Names Word Cloud")
plt.axis('off')
plt.show()

# 9. Project Completed

In [ ]:
print(" Comparative analysis completed successfully.")

# Runtime Prediction : Compare Breast Cancer & Parkinson's

In [ ]:
# ======================================================
# RUNTIME PREDICTION CELL: Compare Breast Cancer & Parkinson's
# ======================================================

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# -------------------------------
# 1. Load or train models (if not already saved)
# -------------------------------
def get_models():
    """Load or train breast cancer and Parkinson's models."""
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.preprocessing import StandardScaler
    from sklearn.datasets import load_breast_cancer
    import pandas as pd

    # ----- Breast Cancer model -----
    try:
        # Try to load saved model
        import joblib
        bc_model = joblib.load('bc_model.pkl')
        bc_scaler = joblib.load('bc_scaler.pkl')
        bc_features = joblib.load('bc_features.pkl')
        print(" Loaded saved Breast Cancer model.")
    except:
        print(" Training Breast Cancer model on‑the‑fly...")
        data = load_breast_cancer()
        X = pd.DataFrame(data.data, columns=data.feature_names)
        y = data.target
        from sklearn.model_selection import train_test_split
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        model.fit(X_scaled, y)
        bc_model = model
        bc_scaler = scaler
        bc_features = list(X.columns)
        # Optionally save for next time
        # joblib.dump(model, 'bc_model.pkl')
        # joblib.dump(scaler, 'bc_scaler.pkl')
        # joblib.dump(bc_features, 'bc_features.pkl')
        print(" Breast Cancer model trained.")

    # ----- Parkinson's Disease model -----
    try:
        import joblib
        pd_model = joblib.load('pd_model.pkl')
        pd_scaler = joblib.load('pd_scaler.pkl')
        pd_features = joblib.load('pd_features.pkl')
        print(" Loaded saved Parkinson's model.")
    except:
        print(" Training Parkinson's model on‑the‑fly...")
        url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/parkinsons.data'
        df_pd = pd.read_csv(url)
        df_pd.drop('name', axis=1, inplace=True)
        X = df_pd.drop('status', axis=1)
        y = df_pd['status']
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        model.fit(X_scaled, y)
        pd_model = model
        pd_scaler = scaler
        pd_features = list(X.columns)
        # joblib.dump(model, 'pd_model.pkl')
        # joblib.dump(scaler, 'pd_scaler.pkl')
        # joblib.dump(pd_features, 'pd_features.pkl')
        print(" Parkinson's model trained.")

    return (bc_model, bc_scaler, bc_features), (pd_model, pd_scaler, pd_features)

(bc_model, bc_scaler, bc_features), (pd_model, pd_scaler, pd_features) = get_models()

# -------------------------------
# 2. Prediction functions
# -------------------------------
def predict_breast_cancer():
    print("\n Breast Cancer Prediction (Malignant/Benign)")
    print("Enter the following 30 cell nuclei measurements (comma‑separated):")
    print("Feature order:", bc_features[:5], "... (total 30)")
    values = input("Enter all 30 values (comma‑separated): ")
    try:
        nums = [float(x.strip()) for x in values.split(',')]
        if len(nums) != len(bc_features):
            print(f" Expected {len(bc_features)} values, got {len(nums)}")
            return
        input_df = pd.DataFrame([nums], columns=bc_features)
        scaled = bc_scaler.transform(input_df)
        prob = bc_model.predict_proba(scaled)[0][1]  # probability of benign (1)
        pred = bc_model.predict(scaled)[0]
        result = "Benign (Non‑cancerous)" if pred == 1 else "Malignant (Cancerous)"
        confidence = prob if pred == 1 else 1 - prob
        print(f"\n Prediction: {result} (confidence {confidence:.2%})")
    except Exception as e:
        print(f"Error: {e}")

def predict_parkinson():
    print("\n Parkinson's Disease Prediction")
    print("Enter the following 22 voice measurements (comma‑separated):")
    print("Feature order:", pd_features[:5], "... (total 22)")
    values = input("Enter all 22 values (comma‑separated): ")
    try:
        nums = [float(x.strip()) for x in values.split(',')]
        if len(nums) != len(pd_features):
            print(f" Expected {len(pd_features)} values, got {len(nums)}")
            return
        input_df = pd.DataFrame([nums], columns=pd_features)
        scaled = pd_scaler.transform(input_df)
        prob = pd_model.predict_proba(scaled)[0][1]  # probability of PD (1)
        pred = pd_model.predict(scaled)[0]
        result = "Parkinson's Disease" if pred == 1 else "Healthy"
        confidence = prob if pred == 1 else 1 - prob
        print(f"\n Prediction: {result} (confidence {confidence:.2%})")
    except Exception as e:
        print(f"Error: {e}")

# -------------------------------
# 3. Interactive menu
# -------------------------------
print("\n" + "="*50)
print("DISEASE PREDICTION COMPARISON TOOL")
print("="*50)
print("Choose an option:")
print("1. Predict Breast Cancer (Malignant/Benign)")
print("2. Predict Parkinson's Disease (Healthy/PD)")
print("3. Exit")

while True:
    choice = input("\nEnter your choice (1/2/3): ").strip()
    if choice == '1':
        predict_breast_cancer()
    elif choice == '2':
        predict_parkinson()
    elif choice == '3':
        print("Exiting. Stay healthy!")
        break
    else:
        print("Invalid choice. Please enter 1, 2, or 3.")